# Generated by Django 2.1.7 on 2019-06-24 19:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budgetID', models.AutoField(db_column='BudgetID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Budget Name', max_length=200)),
                ('startDate', models.DateField(db_column='Start Date', default=datetime.date.today)),
                ('endDate', models.DateField(db_column='End Date', default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryID', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('category', models.CharField(db_column='Category', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('expenseID', models.AutoField(db_column='ExpenseID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('description', models.TextField(db_column='Description')),
                ('date', models.DateField(db_column='Date', default=datetime.date.today)),
                ('amount', models.FloatField(db_column='Amount')),
                ('budgetID', models.ForeignKey(db_column='BudgetID', on_delete=django.db.models.deletion.CASCADE, to='budgets.Budget')),
                ('category', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, to='budgets.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('limitID', models.AutoField(db_column='LimitID', primary_key=True, serialize=False)),
                ('amount', models.FloatField(db_column='Amount')),
                ('budgetID', models.ForeignKey(db_column='BudgetID', on_delete=django.db.models.deletion.CASCADE, to='budgets.Budget')),
                ('categroy', models.ForeignKey(db_column='Category', on_delete=django.db.models.deletion.CASCADE, to='budgets.Category')),
            ],
        ),
    ]
