# Generated by Django 2.1.7 on 2019-06-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='current',
            field=models.BooleanField(db_column='Current Budget', default=True),
        ),
    ]
