# Generated by Django 2.1.7 on 2019-06-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
    ]
