# Generated by Django 2.1.7 on 2019-06-24 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_auto_20190624_2108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category',
        ),
    ]
