# Generated by Django 2.1.7 on 2019-07-09 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgets', '0006_budget_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(db_column='User', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, db_column='Description'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('category', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='limit',
            unique_together={('budgetID', 'category')},
        ),
    ]
